eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8888
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
        lable:  master
        server:
          git:
            uri: https://github.com/liyuanqiong/test-config.git
            search-paths: respo

